project:
  type: book
  output-dir: docs/

book:
  title: "ANÁLISE MULTIVARIADA"
  subtitle: "DE DADOS COM R"
  description: "Uma Introdução à Análise Multivariada de Dados com R"

  author:
  - name: "Breno Cauã Rodrigues da Silva"
    orcid: 0009-0005-9740-2069
    affiliations:
      - name: "Universidade Federal do Pará"
      - name: "Instituto de Ciências Exatas e Naturais"
      - name: "Falculdade de Estatística"

  downloads: [pdf]
  sharing: [twitter, facebook]
  page-navigation: true
  repo-url: https://github.com/csilv7/MULTIVARIATE_DATA_ANALYSIS

  chapters:
    - index.qmd
    - part: "MULTIVARIADA I"
    - part: "MULTIVARIADA II"
      chapters: 
        - MULT2\M2U1.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    number-sections: true
    code-fold: true
    code-tools: true
    code-link: true
    toc-location: right
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    pdf-engine: lualatex
    number-sections: true
    fig-pos: "H"
    indent: true
    header-includes: |
      \usepackage{indentfirst}
      \usepackage{latexsym,amssymb,amsmath,amsfonts}
    papersize: a4
    fontsize: 12pt
    geometry: [left=2cm, top=2cm, right=2cm, bottom=2cm]

lang: pt